###save
GRAPHQL http://localhost:8080/graphql

mutation save {
  save(name: "Anastasia", currency: RUB) {
    id,
    name,
    currency
  }
}

###findById
GRAPHQL http://localhost:8080/graphql

query findById {
  findById(id: "64b2926d61cb873db5102391") {
    id,
    name,
    currency
  }
}

###updateById
GRAPHQL http://localhost:8080/graphql

mutation updateById {
  updateById(id: "64b2926d61cb873db5102391", name: "Stephan", currency: USD) {
    id,
    name,
    currency
  }
}

###deleteById
GRAPHQL http://localhost:8080/graphql

mutation deleteById {
  deleteById(id: "64b2926d61cb873db5102391") {
    message
  }
}

###findAll
GRAPHQL http://localhost:8080/graphql

query findAll {
  findAll {
    id,
    name,
    currency
  }
}
